language: node_js

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: NODE_ENV=development
    - os: windows
      env: CC=clang CXX=clang++ npm_config_clang=1 NODE_ENV=_development
      compiler: clang
install:
  - nvm install 10.16.0
  - npm rebuild node-sass --force
  - npm i -g yarn npm@latest snyk
  - export PATH="$PATH:$(yarn global bin)"
  - npm --depth 10 update url-parse
  - yarn add electron-builder@20.34.0
  - yarn global add retire
  - yarn install
jobs:
  include:
    - stage: Deploy1
      os: osx
      script: "echo deploy1"
    - stage: Deploy2
      os: linux
      script:
        - echo 2387373
        - dir

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
