sudo: required
dist: trusty
language: c

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env: NODE_ENV=development
    - os: linux
      env: CC=clang CXX=clang++ npm_config_clang=1 NODE_ENV=_development
      compiler: clang
jobs:
  include:
    - stage: Deploy1
      os: osx
      script: "echo deploy1"
    - stage: Deploy2
      os: linux
      script: "echo 234"

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"
